=begin
#Visual Crossing Weather API

#Weather Forecast and Historical Weather Data via RESTful API.

The version of the OpenAPI document: 4.6
Contact: info@visualcrossing.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for VisualCrossing::WeatherForecastApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WeatherForecastApi' do
  before do
    # run before each test
    @api_instance = VisualCrossing::WeatherForecastApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WeatherForecastApi' do
    it 'should create an instance of WeatherForecastApi' do
      expect(@api_instance).to be_instance_of(VisualCrossing::WeatherForecastApi)
    end
  end

  # unit tests for visual_crossing_web_services_rest_services_weatherdata_forecast_get
  # Weather Forecast API
  # Provides access to weather forecast information. The forecast is available for up to 15 days at the hourly, 12 hour and daily summary level.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :send_as_datasource 
  # @option opts [Boolean] :allow_asynch 
  # @option opts [Boolean] :short_column_names 
  # @option opts [String] :locations 
  # @option opts [String] :aggregate_hours 
  # @option opts [String] :content_type 
  # @option opts [String] :unit_group 
  # @option opts [String] :key 
  # @return [nil]
  describe 'visual_crossing_web_services_rest_services_weatherdata_forecast_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
