=begin
#Visual Crossing Weather API

#Weather Forecast and Historical Weather Data via RESTful API.

The version of the OpenAPI document: 4.6
Contact: info@visualcrossing.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.0.1

=end

# Common files
require 'visual_crossing/api_client'
require 'visual_crossing/api_error'
require 'visual_crossing/version'
require 'visual_crossing/configuration'

# Models

# APIs
require 'visual_crossing/api/historical_weather_api'
require 'visual_crossing/api/timeline_weather_api15_day_forecast_request_api'
require 'visual_crossing/api/timeline_weather_api_date_range_request_api'
require 'visual_crossing/api/timeline_weather_api_single_date_request_api'
require 'visual_crossing/api/weather_forecast_api'

module VisualCrossing
  class << self
    # Customize default settings for the SDK using block.
    #   VisualCrossing.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
